name:                Tufeu
version:             0.1.0.0
github:              "ReedOei/Tufeu"
license:             BSD3
author:              "Reed Oei"
maintainer:          "oei.reed@gmail.com"
copyright:           "2018 Reed Oei"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ReedOei/Tufeu#readme>

dependencies:
- base >= 4.7 && < 5
- random
- containers
- lens
- mtl

library:
  source-dirs: src

executables:
  Tufeu-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Tufeu

tests:
  Tufeu-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Tufeu
